import type { Theme } from './types';

const EDITOR_FONT_FAMILY = "'JetBrains Mono', Consolas, monospace";
const UI_FONT_FAMILY = "system-ui, -apple-system, 'Segoe UI', sans-serif";

// darask-dark: 真の黒に近い背景。VS Code Dark+ に近い、目に優しい暗いテーマ。
export const darkTheme: Theme = {
  id: 'darask-dark',
  label: 'ダーク',
  kind: 'dark',
  cssVars: {
    '--app-bg': '#0e0e0e',
    '--panel-bg': '#161616',
    '--sidebar-bg': '#161616',
    '--titlebar-bg': '#1c1c1c',
    '--statusbar-bg': '#4da3ff',
    '--statusbar-fg': '#0a1622',
    '--fg': '#d4d4d4',
    '--fg-muted': '#9aa0a6',
    '--fg-faint': '#757c88',
    '--border': '#2b2b2b',
    '--focus-border': '#4da3ff',
    '--accent': '#4da3ff',
    '--accent-fg': '#0a1622',
    '--hover-bg': '#212121',
    '--active-bg': '#2a2a2a',
    '--selection-bg': '#264f78',
    '--tab-bar-bg': '#161616',
    '--tab-active-bg': '#0e0e0e',
    '--tab-active-fg': '#ffffff',
    '--tab-inactive-fg': '#8a8a8a',
    '--input-bg': '#1c1c1c',
    '--input-border': '#3a3a3a',
    '--list-active-bg': '#04395e',
    '--list-active-fg': '#ffffff',
    '--scrollbar-thumb': 'rgba(121,121,121,0.4)',
    '--shadow': 'rgba(0,0,0,0.5)',
    '--error': '#f85149',
    '--warning': '#d29922',
    '--success': '#3fb950',
    '--editor-font-family': EDITOR_FONT_FAMILY,
    '--ui-font-family': UI_FONT_FAMILY,
  },
  monaco: {
    base: 'vs-dark',
    inherit: true,
    rules: [
      { token: 'comment', foreground: '6a9955', fontStyle: 'italic' },
      { token: 'keyword', foreground: '569cd6' },
      { token: 'string', foreground: 'ce9178' },
      { token: 'number', foreground: 'b5cea8' },
      { token: 'type', foreground: '4ec9b0' },
      { token: 'class', foreground: 'c586c0' },
      { token: 'function', foreground: 'dcdcaa' },
      { token: 'variable', foreground: '9cdcfe' },
      { token: 'constant', foreground: '4fc1ff' },
      { token: 'operator', foreground: 'd4d4d4' },
      { token: 'delimiter', foreground: 'b0b0b0' },
      { token: 'tag', foreground: 'd7ba7d' },
      { token: 'attribute.name', foreground: '9cdcfe' },
    ],
    colors: {
      'editor.background': '#0e0e0e',
      'editor.foreground': '#d4d4d4',
      'editorLineNumber.foreground': '#5a5a5a',
      'editorLineNumber.activeForeground': '#d4d4d4',
      'editor.selectionBackground': '#264f78',
      'editor.inactiveSelectionBackground': '#264f7866',
      'editor.lineHighlightBackground': '#1a1a1a',
      'editorCursor.foreground': '#4da3ff',
      'editorWidget.background': '#252526',
      'editorWidget.border': '#454545',
      'minimap.background': '#181818',
      'scrollbarSlider.background': 'rgba(121,121,121,0.3)',
      'scrollbarSlider.hoverBackground': 'rgba(121,121,121,0.45)',
    },
  },
};
