import type { Theme } from './types';

const EDITOR_FONT_FAMILY = "'JetBrains Mono', Consolas, monospace";
const UI_FONT_FAMILY = "system-ui, -apple-system, 'Segoe UI', sans-serif";

// darask-light: 白背景。VS Code Light+ に近い、見慣れた明るいテーマ。
export const lightTheme: Theme = {
  id: 'darask-light',
  label: 'ライト',
  kind: 'light',
  cssVars: {
    '--app-bg': '#ffffff',
    '--panel-bg': '#f3f3f3',
    '--sidebar-bg': '#f3f3f3',
    '--titlebar-bg': '#e8e8e8',
    '--statusbar-bg': '#0969da',
    '--statusbar-fg': '#ffffff',
    '--fg': '#1f1f1f',
    '--fg-muted': '#57606a',
    '--fg-faint': '#6e7781',
    '--border': '#d0d7de',
    '--focus-border': '#0969da',
    '--accent': '#0969da',
    '--accent-fg': '#ffffff',
    '--hover-bg': '#eef1f4',
    '--active-bg': '#e2e6ea',
    '--selection-bg': '#add6ff',
    '--tab-bar-bg': '#f3f3f3',
    '--tab-active-bg': '#ffffff',
    '--tab-active-fg': '#1f1f1f',
    '--tab-inactive-fg': '#6e7681',
    '--input-bg': '#ffffff',
    '--input-border': '#d0d7de',
    '--list-active-bg': '#e8f0fe',
    '--list-active-fg': '#1f1f1f',
    '--scrollbar-thumb': 'rgba(100,100,100,0.4)',
    '--shadow': 'rgba(0,0,0,0.16)',
    '--error': '#cf222e',
    '--warning': '#9a6700',
    '--success': '#1a7f37',
    '--editor-font-family': EDITOR_FONT_FAMILY,
    '--ui-font-family': UI_FONT_FAMILY,
  },
  monaco: {
    base: 'vs',
    inherit: true,
    rules: [
      { token: 'comment', foreground: '008000', fontStyle: 'italic' },
      { token: 'keyword', foreground: '0000ff' },
      { token: 'string', foreground: 'a31515' },
      { token: 'number', foreground: '0a7a4e' },
      { token: 'type', foreground: '236f87' },
      { token: 'class', foreground: '6f42c1' },
      { token: 'function', foreground: '795e26' },
      { token: 'variable', foreground: '001080' },
      { token: 'constant', foreground: '811f3f' },
      { token: 'operator', foreground: '3b3b3b' },
      { token: 'delimiter', foreground: '545454' },
      { token: 'tag', foreground: '800000' },
      { token: 'attribute.name', foreground: 'e50000' },
    ],
    colors: {
      'editor.background': '#ffffff',
      'editor.foreground': '#1f1f1f',
      'editorLineNumber.foreground': '#8a8a8a',
      'editorLineNumber.activeForeground': '#1f1f1f',
      'editor.selectionBackground': '#add6ff',
      'editor.inactiveSelectionBackground': '#add6ff66',
      'editor.lineHighlightBackground': '#f5f5f5',
      'editorCursor.foreground': '#0969da',
      'editorWidget.background': '#f3f3f3',
      'editorWidget.border': '#c8c8c8',
      'minimap.background': '#f8f8f8',
      'scrollbarSlider.background': 'rgba(100,100,100,0.3)',
      'scrollbarSlider.hoverBackground': 'rgba(100,100,100,0.45)',
    },
  },
};
