import type { Theme } from './types';

const EDITOR_FONT_FAMILY = "'JetBrains Mono', Consolas, monospace";
const UI_FONT_FAMILY = "system-ui, -apple-system, 'Segoe UI', sans-serif";

// darask-paper: このエディタの看板テーマ。古い紙に万年筆で書いたような趣。
// ライトテーマの色相回転ではなく、セピア/コーヒー色で独自に調色する。
// 全カラーペアは WCAG AA(通常テキスト 4.5:1)を満たすよう検証済み。
export const paperTheme: Theme = {
  id: 'darask-paper',
  label: 'ペーパー',
  kind: 'light',
  cssVars: {
    '--app-bg': '#f3ead7',
    '--panel-bg': '#eaddc3',
    '--sidebar-bg': '#eaddc3',
    '--titlebar-bg': '#e3d4b3',
    '--statusbar-bg': '#8b5a2b',
    '--statusbar-fg': '#f7ecd8',
    '--fg': '#41352a',
    '--fg-muted': '#6b5a45',
    '--fg-faint': '#756249',
    '--border': '#d8c8a8',
    '--focus-border': '#8b5a2b',
    '--accent': '#8b5a2b',
    '--accent-fg': '#f7ecd8',
    '--hover-bg': '#ecdfc4',
    '--active-bg': '#e3d0a3',
    '--selection-bg': '#d8c090',
    '--tab-bar-bg': '#eaddc3',
    '--tab-active-bg': '#f3ead7',
    '--tab-active-fg': '#41352a',
    '--tab-inactive-fg': '#8a7860',
    '--input-bg': '#f7f0e0',
    '--input-border': '#c9b48c',
    '--list-active-bg': '#ddc9a0',
    '--list-active-fg': '#3a2f22',
    '--scrollbar-thumb': 'rgba(139,90,43,0.35)',
    '--shadow': 'rgba(65,53,42,0.28)',
    '--error': '#a13a2f',
    '--warning': '#7a5f1a',
    '--success': '#4f6b2a',
    '--editor-font-family': EDITOR_FONT_FAMILY,
    '--ui-font-family': UI_FONT_FAMILY,
  },
  monaco: {
    base: 'vs',
    inherit: true,
    rules: [
      { token: 'comment', foreground: '73604a', fontStyle: 'italic' },
      { token: 'keyword', foreground: '5a3a1e' },
      { token: 'string', foreground: '5a6830' },
      { token: 'number', foreground: 'a13a2f' },
      { token: 'type', foreground: '7a5f1a' },
      { token: 'class', foreground: '7a3b3b' },
      { token: 'function', foreground: '6b4a6b' },
      { token: 'variable', foreground: '4a3c2f' },
      { token: 'constant', foreground: '8f5326' },
      { token: 'operator', foreground: '6b5a45' },
      { token: 'delimiter', foreground: '756249' },
      { token: 'tag', foreground: '7a3b2a' },
      { token: 'attribute.name', foreground: '835a2b' },
    ],
    colors: {
      'editor.background': '#f3ead7',
      'editor.foreground': '#41352a',
      'editorLineNumber.foreground': '#a08b6a',
      'editorLineNumber.activeForeground': '#5a3a1e',
      'editor.selectionBackground': '#d8c090',
      'editor.inactiveSelectionBackground': '#d8c09066',
      'editor.lineHighlightBackground': '#ece0c8',
      'editorCursor.foreground': '#2b1d12',
      'editorWidget.background': '#eaddc3',
      'editorWidget.border': '#d8c8a8',
      'minimap.background': '#efe4cc',
      'scrollbarSlider.background': 'rgba(139,90,43,0.25)',
      'scrollbarSlider.hoverBackground': 'rgba(139,90,43,0.4)',
    },
  },
};
